version: '3'
services:
  web:
    build:
      context: '.'
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=boilerplate-database
      - DB_USER=boilerplate-database-username
      - DB_PASSWORD=boilerplate-database-password
      - JWT_SECRET_KEY=Mdc6PVaq-q*sxFnFjvA@LhAs
      - JWT_EXPIRATION_SECONDS=3600
#      - DEBUG=loopback:*
    networks:
      - boilerplate-network
    volumes:
      - .:/home/node/app
    command: nodemon -e ts,json --ignore './dist' --watch /home/node/app/src --exec "yarn run start:dev"
#    command: "yarn run start"
  mongo:
    image: "mongo:7.0.1"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=boilerplate-database
      - MONGO_INITDB_ROOT_USERNAME=boilerplate-database-username
      - MONGO_INITDB_ROOT_PASSWORD=boilerplate-database-password
    networks:
      - boilerplate-network
    volumes:
      - boilerplate-mongo:/data/db
  mongo_test:
    image: "mongo:7.0.1"
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=test-database
      - MONGO_INITDB_ROOT_USERNAME=boilerplate-database-username
      - MONGO_INITDB_ROOT_PASSWORD=boilerplate-database-password
    networks:
      - boilerplate-network
    volumes:
      - boilerplate-mongo-test:/data/db
networks:
  boilerplate-network:
    driver: bridge

volumes:
  boilerplate-web-app:
  boilerplate-mongo:
  boilerplate-mongo-test: